/* USERS */
export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const POST_USER = "POST_USER"
export const POST_USER_SUCCESS = "POST_USER_SUCCESS"
export const POST_USER_FAIL = "POST_USER_FAIL"
export const TOGGLE_MODAL_CREATE_USER = "TOGGLE_MODAL_CREATE_USER"

export const PUT_USER = "PUT_USER"
export const TOGGLE_MODAL_EDIT_USER = "TOGGLE_MODAL_EDIT_USER"
export const DELETE_USER = "DELETE_USER"

export const GET_ROLES = "GET_ROLES"
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS"
export const GET_DEPARTMENTS = "GET_DEPARTMENTS"
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS"

export const GET_SENDERS = "GET_SENDERS"
export const GET_SENDERS_SUCCESS = "GET_SENDERS_SUCCESS"
export const GET_SENDERS_FAIL = "GET_SENDERS_FAIL"
export const API_ERROR = "API_ERROR"

export const GET_TEAMS = "GET_TEAMS"
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS"
export const GET_TEAMS_FAIL = "GET_TEAMS_FAIL"
export const POST_TEAM = "POST_TEAM"
export const POST_TEAM_SUCCESS = "POST_TEAM_SUCCESS"
export const POST_TEAM_FAIL = "POST_TEAM_FAIL"
export const TOGGLE_CARD_CREATE_TEAM = "TOGGLE_CARD_CREATE_TEAM"

export const TOGGLE_CARD_EDIT_TEAM = "TOGGLE_CARD_EDIT_TEAM"
export const PUT_TEAM = "PUT_TEAM"
export const DELETE_TEAM = "DELETE_TEAM"

export const TOGGLE_PROFILE_EDIT = "TOGGLE_PROFILE_EDIT"
export const GET_PROFILE = "GET_PROFILE"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"
export const PUT_PROFILE = "PUT_PROFILE"

export const GET_PROFILE_TEAMS = "GET_PROFILE_TEAMS"
export const GET_PROFILE_TEAMS_SUCCESS = "GET_PROFILE_TEAMS_SUCCES"
export const GET_PROFILE_TICKETS = "GET_PROFILE_TICKETS"
export const GET_PROFILE_TICKETS_SUCCESS = "GET_PROFILE_TICKETS_SUCCESS"
export const GET_PROFILE_TICKETS_ASSIGN = "GET_PROFILE_TICKETS_ASSIGN"
export const GET_PROFILE_TICKETS_ASSIGN_SUCCESS = "GET_PROFILE_TICKETS_ASSIGN_SUCCESS"

export const GET_TEAM_MANAGER = "GET_TEAM_MANAGER"
export const GET_TEAM_MEMBER = "GET_TEAM_MEMBER"



