/* TICKETS */
export const GET_TICKETS = "GET_TICKETS"
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS"
export const GET_TICKETS_FAIL = "GET_TICKETS_FAIL"

export const CREATE_TICKETS = "CREATE_TICKETS"
export const CREATE_TICKETS_SUCCESS = "CREATE_TICKETS_SUCCESS"
export const CREATE_TICKETS_FAIL = "CREATE_TICKETS_FAIL"

export const CHANGE_TICKETS = "CHANGE_TICKETS"
export const CHANGE_ACTIVE_TAB = "CHANGE_ACTIVE_TAB"

export const TOGGLE_MODAL_CREATE = "TOGGLE_MODAL_CREATE"
export const GET_ACTION_LIST = "GET_ACTION_LIST"

export const GET_OPTION_LIST = "GET_OPTION_LIST"
export const GET_OPTION_LIST_SUCCESS = "GET_OPTION_LIST_SUCCESS"

export const GRIDVIEW_SELECTED_ROW = "GRIDVIEW_SLECTED_ROW"
export const GRIDVIEW_SELECTED_ROW_SUCCESS = "GRIDVIEW_SLECTED_ROW_SUCCESS"
export const GRIDVIEW_MULTISELECTED_ROW = "GRIDVIEW_MULTISELECTED_ROW"

export const TOGGLE_DRAWER_EDITOR = "TOGGLE_DRAWER_EDITOR"

export const POST_TICKET_DETAIL = "POST_TICKET_DEATAIL"
export const POST_TICKET_DETAIL_SUCCESS = "POST_TICKET_DEATAIL_SUCCESS"
export const POST_TICKET_DETAIL_FAIL = "POST_TICKET_DEATAIL_FAIL"

export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS"
export const UPDATE_TICKET_STATUS_SUCCESS = "UPDATE_TICKET_STATUS_SUCCESS"

export const POST_TICKET_ASSIGN = "POST_TICKET_ASSIGN"
export const POST_TICKET_ASSIGN_SUCCESS = "POST_TICKET_ASSIGN_SUCCESS"
// export const 

export const UPDATE_TICKET_ASSIGN_VIEWED = "UPDATE_TICKET_ASSIGN_VIEWED"
export const UPDATE_TICKET_COMMENT = "UPDATE_TICKET_COMMENT"
export const DELETE_TICKET_COMMENT = "DELETE_TICKET_COMMENT"

export const GET_FILTERED_SEACRH_TICKET = "GET_FILTERED_SEACRH_TICKET"
export const GET_FILTERED_SEACRH_TICKET_SUCCESS = "GET_FILTERED_SEACRH_TICKET_SUCCESS"


export const RESET_TICKET_STATE = "RESET_TICKET_STATE"

export const ACTIVE_TAB_TYPE = {
     ALL : '1',
     NEW_ASSIGNED : '2',
     UNASSIGNED: '3',
     PENDING: '4',
     RECENTLY_UPDATE: '5',
     RECENTLY_SOLVED: '6',
     DELETED: '7',
     INPROGRESS: '8'
}

export const TICKET_ERROR_TYPE = {
     CREATE_TICKET: "CREATE_TICKET"
}


export const GET_PRIORITY         = "GET_PRIORITY"
export const GET_PRIORITY_SUCCESS = "GET_PRIORITY_SUCCESS"
export const GET_PRIORITY_FAIL    = "GET_PRIORITY_FAIL"

export const GET_ENHANCEMENT            = "GET_ENHANCEMENT"
export const GET_ENHANCEMENT_SUCCESS    = "GET_ENHANCEMENT_SUCCESS"
export const GET_ENHANCEMENT_FAIL       = "GET_ENHANCEMENT_FAIL"

export const PUT_PRIORITY_ENHANCE         = "PUT_PRIORITY_ENHANCE"

export const GET_DB_LIST = "GET_DB_LIST"
export const GET_DB_LIST_SUCCESS = "GET_DB_LIST_SUCCESS"
export const CHANGE_DB_ACTIVE = "CHANGE_DB_ACTIVE"




