/* USERS */


export const INIT_FIREBASE = "INIT_FIREBASE"
export const INIT_FIREBASE_SUCCESS = "INIT_FIREBASE_SUCCESS"
export const ASK_PERMISSION_NOTIF = "ASK_PERMISSION_NOTIF"
export const SET_APP_MSG_NTF = "SET_APP_MSG_NTF"
export const ADD_REGISTERED_FCM = "ADD_REGISTERED_FCM"

export const SET_CONNECTION_HUB = "SET_CONNECTION_HUB"
export const REMOVE_CONNECTION_HUB = "REMOVE_CONNECTION_HUB"

export const GET_NOTIFS = "GET_NOTIFS"
export const GET_NOTIFS_SUCCESS = "GET_NOTIFS_SUCCESS"
export const GET_NOTIFS_FAIL = "GET_NOTIFS_FAIL"

export const PUT_NOTIFS = "PUT_NOTIFS"
export const PUT_NOTIFS_SUCCESS = "PUT_NOTIFS_SUCCESS"
export const PUT_NOTIFS_FAIL = "PUT_NOTIFS_FAIL"

export const RESET_NOTIF_STATE = "RESET_NOTIF_STATE"

export const CHECKING_NOTIF_COUNT = "CHECKING_NOTIF_COUNT"
export const CHECKING_NOTIF_COUNT_SUCCESS = "CHECKING_NOTIF_COUNT_SUCCESS"

export const MARK_ALL_NOTIF = "MARK_ALL_NOTIF"
export const MARK_ALL_NOTIF_SUCCESS = "MARK_ALL_NOTIF_SUCCESS"

export const NOTIF_TYPE_TICKET_CREATE = "TICKET_CREATE";
export const NOTIF_TYPE_TICKET_ASSIGN = "TICKET_ASSIGN";
export const NOTIF_TYPE_TICKET_STATUS = "TICKET_STATUS";
export const NOTIF_TYPE_TICKET_RESPONSE = "TICKET_RESPONSE";