export const GET_KBASES = "GET_KBASES"
export const GET_KBASES_SUCCESS = "GET_KBASES_SUCCESS"
export const GET_KBASES_FAIL = "GET_KBASES_FAIL"

export const GET_KBASES_BYID = "GET_KBASES_BYID"
export const GET_KBASES_BYID_SUCCESS = "GET_KBASES_BYID_SUCCESS"
export const GET_KBASES_BYID_FAIL = "GET_KBASES_BYID_FAIL"

export const GET_KBASES_BY_APP = "GET_KBASES_BY_APP"
export const GET_KBASES_BY_APP_SUCCESS = "GET_KBASES_BY_APP_SUCCESS"
export const GET_KBASES_BY_APP_FAIL = "GET_KBASES_BY_APP_FAIL"

export const POST_KBASE = "POST_KBASE"
export const POST_KBASE_SUCCESS = "POST_KBASE_SUCCESS"
export const POST_KBASE_FAIL = "POST_KBASE_FAIL"
export const TOGGLE_MODAL_CREATE_KBASE = "TOGGLE_MODAL_CREATE_KBASE"

export const PUT_KBASE = "PUT_KBASE"
export const TOGGLE_MODAL_EDIT_KBASE = "TOGGLE_MODAL_EDIT_KBASE"
export const DELETE_KBASE = "DELETE_KBASE"

export const DO_FILTER_KBASES = "DO_FILTER_KBASES"

export const RESET_KBASE_STATE = "RESET_KBASE_STATE"

export const CHANGE_MODULE_ACTIVE = "CHANGE_MODULE_ACTIVE"
export const CHANGE_APP_ACTIVE = "CHANGE_APP_ACTIVE"