export const GET_GROUP_AGENCY = "GET_GROUP_AGENCY"
export const GET_GROUP_AGENCY_SUCCESS = "GET_GROUP_AGENCY_SUCCESS"
export const GET_GROUP_AGENCY_FAIL = "GET_GROUP_AGENCY_FAIL"

export const GET_AGENCY = "GET_AGENCY"
export const GET_AGENCY_SUCCESS = "GET_AGENCY_SUCCESS"
export const GET_AGENCY_FAIL = "GET_AGENCY_FAIL"

export const SET_CHANGES = "SET_CHANGES"
export const SET_EDIT_ROW_KEY = "SET_EDIT_ROW_KEY"

export const POST_GROUP_AGENCY = "POST_GROUP_AGENCY"
export const POST_GROUP_AGENCY_SUCCESS = "POST_GROUP_AGENCY_SUCCESS"
export const POST_GROUP_AGENCY_FAIL = "POST_GROUP_AGENCY_FAIL"

export const PUT_GROUP_AGENCY = "PUT_GROUP_AGENCY"
export const PUT_GROUP_AGENCY_SUCCESS = "PUT_GROUP_AGENCY_SUCCESS"
export const PUT_GROUP_AGENCY_FAIL = "PUT_GROUP_AGENCY_FAIL"

export const DELETE_GROUP_AGENCY = "DELETE_GROUP_AGENCY"
export const DELETE_GROUP_AGENCY_SUCCESS = "DELETE_GROUP_AGENCY_SUCCESS"
export const DELETE_GROUP_AGENCY_FAIL = "DELETE_GROUP_AGENCY_FAIL"

export const SET_CHANGES_DETAIL = "SET_CHANGES_DETAIL"
export const SET_EDIT_ROW_KEY_DETAIL = "SET_EDIT_ROW_KEY_DETAIL"

export const POST_AGENCY = "POST_AGENCY"
export const POST_AGENCY_SUCCESS = "POST_AGENCY_SUCCESS"
export const POST_AGENCY_FAIL = "POST_AGENCY_FAIL"

export const PUT_AGENCY = "PUT_AGENCY"
export const PUT_AGENCY_SUCCESS = "PUT_AGENCY_SUCCESS"
export const PUT_AGENCY_FAIL = "PUT_AGENCY_FAIL"

export const DELETE_AGENCY = "DELETE_AGENCY"
export const DELETE_AGENCY_SUCCESS = "DELETE_AGENCY_SUCCESS"
export const DELETE_AGENCY_FAIL = "DELETE_AGENCY_FAIL"





export const RESET_GROUP_AGENCY_STATE = "RESET_GROUP_AGENCY_STATE"