export const LOGIN_CLIENT = "LOGIN_CLIENT"
export const LOGIN_CLIENT_SUCCESS = "LOGIN_CLIENT_SUCCESS"

export const FPASSWORD_CLIENT = "FPASSWORD_CLIENT"
export const FPASSWORD_CLIENT_SUCCESS = "FPASSWORD_CLIENT_SUCCESS"

export const REGISTER_CLIENT = "REGISTER_CLIENT"
export const REGISTER_CLIENT_SUCCESS = "REGISTER_CLIENT_SUCCESS"


export const LOGOUT_CLIENT = "LOGOUT_CLIENT"
export const LOGOUT_CLIENT_SUCCESS = "LOGOUT_CLIENT_SUCCESS"


export const VERIFICATION_MAIL_CHECK = "VERIFICATION_MAIL_CHECK"
export const VERIFICATION_MAIL_CHECK_SUCCESS = "VERIFICATION_MAIL_CHECK_SUCCESS"

export const AUTHENTICATE_CLIENT_CHECK = "AUTHENTICATE_CLIENT_CHECK"
export const AUTHENTICATE_CLIENT_CHECK_SUCCESS = "AUTHENTICATE_CLIENT_CHECK_SUCCESS"

export const REQ_FREE_TOKEN = "REQ_FREE_TOKEN"
export const REQ_FREE_TOKEN_SUCCESS = "REQ_FREE_TOKEN_SUCCESS"


export const CLIENT_API_ERROR = "CLIENT_API_ERROR"
export const RESET_CLIENT_AUTH_STATE = "RESET_CLIENT_AUTH_STATE"



