/* USERS */
export const GET_DASHBOARD_TICKET = "GET_DASHBOARD_TICKET"
export const GET_DASHBOARD_TICKET_SUCCESS = "GET_DASHBOARD_TICKET_SUCCESS"
export const GET_DASHBOARD_TICKET_FAIL = "GET_DASHBOARD_TICKET_FAIL"
