export const GET_FAQS = "GET_FAQS"
export const GET_FAQS_SUCCESS = "GET_FAQS_SUCCESS"
export const GET_FAQS_FAIL = "GET_FAQS_FAIL"

export const GET_FAQS_BY_APP = "GET_FAQS_BY_APP"
export const GET_FAQS_BY_APP_SUCCESS = "GET_FAQS_BY_APP_SUCCESS"
export const GET_FAQS_BY_APP_FAIL = "GET_FAQS_BY_APP_FAIL"

export const POST_FAQ = "POST_FAQ"
export const POST_FAQ_SUCCESS = "POST_FAQ_SUCCESS"
export const POST_FAQ_FAIL = "POST_FAQ_FAIL"
export const TOGGLE_MODAL_CREATE_FAQ = "TOGGLE_MODAL_CREATE_FAQ"

export const PUT_FAQ = "PUT_FAQ"
export const TOGGLE_MODAL_EDIT_FAQ = "TOGGLE_MODAL_EDIT_FAQ"
export const DELETE_FAQ = "DELETE_FAQ"

export const GET_FAQ_TYPE = "GET_FAQ_TYPE"
export const GET_FAQ_TYPE_SUCCESS = "GET_FAQ_TYPE_SUCCESS"
export const GET_FAQ_TYPE_FAIL = "GET_FAQ_TYPE_FAIL"

export const GET_LATEST_VER_APP = "GET_LATEST_VER_APP"
export const GET_LATEST_VER_APP_SUCCESS = "GET_LATEST_VER_APP_SUCCESS"
export const GET_LATEST_VER_APP_FAIL = "GET_LATEST_VER_APP_FAIL"

export const DO_FILTER_FAQS = "DO_FILTER_FAQS"

export const RESET_FAQ_STATE = "RESET_FAQ_STATE"


export const CHANGE_MODULE_TAB_ACTIVE = "CHANGE_MODULE_TAB_ACTIVE"
export const CHANGE_APP_ACTIVE = "CHANGE_APP_ACTIVE"