/* USERS */
export const GET_CLOGS = "GET_CLOGS"
export const GET_CLOGS_SUCCESS = "GET_CLOGS_SUCCESS"
export const GET_CLOGS_FAIL = "GET_CLOGS_FAIL"

export const POST_CLOG = "POST_CLOG"
export const POST_CLOG_SUCCESS = "POST_CLOG_SUCCESS"
export const POST_CLOG_FAIL = "POST_CLOG_FAIL"
export const TOGGLE_MODAL_CREATE_CLOG = "TOGGLE_MODAL_CREATE_CLOG"

export const PUT_CLOG = "PUT_CLOG"
export const TOGGLE_MODAL_EDIT_CLOG = "TOGGLE_MODAL_EDIT_CLOG"
export const DELETE_CLOG = "DELETE_CLOG"

export const GET_CLOG_TYPE = "GET_CLOG_TYPE"
export const GET_CLOG_TYPE_SUCCESS = "GET_CLOG_TYPE_SUCCESS"
export const GET_CLOG_TYPE_FAIL = "GET_CLOG_TYPE_FAIL"

export const GET_LATEST_VER_APP = "GET_LATEST_VER_APP"
export const GET_LATEST_VER_APP_SUCCESS = "GET_LATEST_VER_APP_SUCCESS"
export const GET_LATEST_VER_APP_FAIL = "GET_LATEST_VER_APP_FAIL"

export const GET_LATEST_CLOG =         "GET_LATEST_CLOG"
export const GET_LATEST_CLOG_SUCCESS = "GET_LATEST_CLOG_SUCCESS"
export const GET_LATEST_CLOG_FAIL =    "GET_LATEST_CLOG_FAIL"

export const DO_FILTER_CLOGS = "DO_FILTER_CLOGS"

export const SET_APP_ACTIVE = "SET_APP_ACTIVE"


export const RESET_CLOG_STATE = "RESET_CLOG_STATE"