/* TICKETS */
export const GET_CLIENT_TICKETS = "GET_CLIENT_TICKETS"
export const GET_CLIENT_TICKETS_SUCCESS = "GET_CLIENT_TICKETS_SUCCESS"
export const GET_CLIENT_TICKETS_FAIL = "GET_CLIENT_TICKETS_FAIL"
export const CHANGE_CLIENT_ACTIVE_TICKET  = "CHANGE_CLIENT_ACTIVE_TICKET"


export const POST_CLIENT_TICKET_DETAIL = "POST_CLIENT_TICKET_DETAIL"
export const POST_CLIENT_TICKET_DETAIL_SUCCESS = "POST_CLIENT_TICKET_DETAIL_SUCCESS"
export const POST_CLIENT_TICKET_DETAIL_FAIL = "POST_CLIENT_TICKET_DETAIL_FAIL"


export const CREATE_CLIENT_TICKETS = "CREATE_CLIENT_TICKETS"
export const CREATE_CLIENT_TICKETS_SUCCESS = "CREATE_CLIENT_TICKETS_SUCCESS"
export const CREATE_CLIENT_TICKETS_FAIL = "CREATE_CLIENT_TICKETS_FAIL"

export const TOGGLE_VERIFY_OPEN_TICKET = "TOGGLE_VERIFY_OPEN_TICKET"
export const GET_VERIFY_OPEN_TICKET = "GET_VERIFY_OPEN_TICKET"
export const GET_VERIFY_OPEN_TICKET_SUCCESS = "GET_VERIFY_OPEN_TICKET_SUCCESS"
export const GET_VERIFY_OPEN_TICKET_FAIL = "TOGGLE_VERIFY_OPEN_FAIL"

export const RESET_CLIENT_TICKET_STATE = "RESET_CLIENT_TICKET_STATE"












// export const CHANGE_TICKETS = "CHANGE_TICKETS"
// export const CHANGE_ACTIVE_TAB = "CHANGE_ACTIVE_TAB"

// export const TOGGLE_MODAL_CREATE = "TOGGLE_MODAL_CREATE"
// export const GET_ACTION_LIST = "GET_ACTION_LIST"

// export const GET_OPTION_LIST = "GET_OPTION_LIST"
// export const GET_OPTION_LIST_SUCCESS = "GET_OPTION_LIST_SUCCESS"

// export const GRIDVIEW_SELECTED_ROW = "GRIDVIEW_SLECTED_ROW"
// export const GRIDVIEW_MULTISELECTED_ROW = "GRIDVIEW_MULTISELECTED_ROW"

// export const TOGGLE_DRAWER_EDITOR = "TOGGLE_DRAWER_EDITOR"


// export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS"
// export const UPDATE_TICKET_STATUS_SUCCESS = "UPDATE_TICKET_STATUS_SUCCESS"

// export const POST_TICKET_ASSIGN = "POST_TICKET_ASSIGN"
// export const POST_TICKET_ASSIGN_SUCCESS = "POST_TICKET_ASSIGN_SUCCESS"
// // export const 

// export const UPDATE_TICKET_ASSIGN_VIEWED = "UPDATE_TICKET_ASSIGN_VIEWED"
// export const UPDATE_TICKET_COMMENT = "UPDATE_TICKET_COMMENT"
// export const DELETE_TICKET_COMMENT = "DELETE_TICKET_COMMENT"

// export const ACTIVE_TAB_TYPE = {
//      ALL : '1',
//      NEW_ASSIGNED : '2',
//      UNASSIGNED: '3',
//      PENDING: '4',
//      RECENTLY_UPDATE: '5',
//      RECENTLY_SOLVED: '6',
//      DELETED: '7' 
// }

